---
title: "Knitting Needles"
editor: visual
---

```{r setup, include=FALSE}

library(tidyverse)

needles <- read_csv("data/k_needles.csv", col_types = "cccicc") %>%
  filter(verified == "x" & is.na(incomplete)) %>% 
  arrange(size) %>% 
  mutate(length = if_else(length == "17","16",length))
```

## What knitting needles do I have?

### A practical guide

```{r general needles, echo=FALSE, message=FALSE, warning=FALSE}

k_needles <- needles %>% 
  mutate(type_or_length = case_when(
      type == "straight"  ~ "straight",
      type == "dpn"       ~ "dpn",
      type == "hook"      ~ "hook", 
      type == "circular"  ~ length
    )
  ) %>% 
  group_by(size, type_or_length) %>% 
  summarise(qty = sum(qty)) %>% 
  ungroup()

k_needles %>% 
  pivot_wider(names_from = type_or_length, values_from = qty) %>% 
  pivot_longer(cols = -size, names_to = "type_or_length", values_to = "qty") %>% 
  ggplot(mapping = aes(x = fct_relevel(size, c("00000", "0000", "000", "00", "0", "1", "1.5", "2", "2.5", "3", "4", "5", "6", "7", "8", "9", "10", "10.5", "11")), y = fct_relevel(type_or_length, c("dpn", "9","12", "16", "24", "32", "36", "40", "47", "60", "straight", "hook")), fill = qty)) +
  geom_tile(color = "grey", size = 0.25) +
  coord_flip() +
  labs(x = "Size", y = "Type") +
  theme_bw() +
  scale_fill_continuous(na.value = "white") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0))


```

### Wooden needles

```{r wooden needles, echo=FALSE, message=FALSE, warning=FALSE}
wood_needles <- needles %>% 
  mutate(type_or_length = case_when(
      type == "straight"  ~ "straight",
      type == "dpn"       ~ "dpn",
      type == "hook"      ~ "hook",
      type == "circular"  ~ length
    )
  ) %>% 
  filter(material == "wood") %>%
  group_by(size, type_or_length) %>% 
  summarise(qty = sum(qty)) %>% 
  ungroup()

wood_needles %>% 
  pivot_wider(names_from = type_or_length, values_from = qty) %>% 
  pivot_longer(cols = -size, names_to = "type_or_length", values_to = "qty") %>% 
  ggplot(mapping = aes(x = fct_relevel(size, c("00000", "0000", "000", "00", "0", "1", "1.5", "2", "2.5", "3", "4", "5", "6", "7", "8", "9", "10", "10.5", "11")), y = fct_relevel(type_or_length, c("dpn", "9","12", "16", "24", "32", "36", "40", "47", "60", "straight", "hook")), fill = qty)) +
  geom_tile(color = "grey", size = 0.25) +
  coord_flip() +
  labs(x = "Size", y = "Type") +
  theme_bw() +
  scale_fill_gradient(low="brown", high="orange", na.value = "White") +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0))

```

### Bamboo needles

```{r bamboo needles, echo=FALSE, message=FALSE, warning=FALSE}
bamboo_needles <- needles %>% 
  mutate(type_or_length = case_when(
      type == "straight"  ~ "straight",
      type == "dpn"       ~ "dpn",
      type == "hook"      ~ "hook", 
      type == "circular"  ~ length
    )
  ) %>% 
  filter(material == "bamboo") %>%
  group_by(size, type_or_length) %>% 
  summarise(qty = sum(qty)) %>% 
  ungroup()

bamboo_needles %>% 
  pivot_wider(names_from = type_or_length, values_from = qty) %>% 
  pivot_longer(cols = -size, names_to = "type_or_length", values_to = "qty") %>% 
  ggplot(mapping = aes(x = fct_relevel(size, c("00000", "0000", "000", "00", "0", "1", "1.5", "2", "2.5", "3", "4", "5", "6", "7", "8", "9", "10", "10.5", "11")), y = fct_relevel(type_or_length, c("dpn", "9","12", "16", "24", "32", "36", "40", "47", "60", "straight", "hook")), fill = qty)) +
  geom_tile(color = "grey", size = 0.25) +
  coord_flip() +
  labs(x = "Size", y = "Type") +
  theme_bw() +
  scale_fill_gradient(low="blue", high="green", na.value = "White")+
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0))

```


### Metal needles

```{r metal needles, echo=FALSE, message=FALSE, warning=FALSE}
metal_needles <- needles %>% 
  mutate(type_or_length = case_when(
      type == "straight"  ~ "straight",
      type == "dpn"       ~ "dpn",
      type == "hook"      ~ "hook",
      type == "circular"  ~ length
    )
  ) %>% 
  filter(material == "metal") %>%
  group_by(size, type_or_length) %>% 
  summarise(qty = sum(qty)) %>% 
  ungroup()

metal_needles %>% 
  pivot_wider(names_from = type_or_length, values_from = qty) %>% 
  pivot_longer(cols = -size, names_to = "type_or_length", values_to = "qty") %>% 
  ggplot(mapping = aes(x = fct_relevel(size, c("00000", "0000", "000", "00", "0", "1", "1.5", "2", "2.5", "3", "4", "5", "6", "7", "8", "9", "10", "10.5", "11")), y = fct_relevel(type_or_length, c("dpn", "9","12", "16", "24", "32", "36", "40", "47", "60", "straight", "hook")), fill = qty)) +
  geom_tile(color = "grey", size = 0.25) +
  coord_flip() +
  labs(x = "Size", y = "Type") +
  theme_bw() +
  scale_fill_gradient(low="black", high="purple", na.value = "White")+
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0))

```